### PR TITLE
New: method to get stored reports by ids

### PR DESCRIPTION
**Pull request by double-beep**

### CODE REVIEW

**Comment by Bhargav-Rao** [comment]
Can you add some examples of the response from this endpoint?

**Comment by double-beep** [comment]
Assume `/napi/api/stored/all` returns:

```
{
  "items": [
    {
      "name": "1234",
      "type": "Stored post"
    },
    {
      "name": "5678",
      "type": "Stored post"
    },
    {
      "name": "1235",
      "type": "Stored post"
    },
    {
      "name": "5658",
      "type": "Stored post"
    }
  ],
  "message": "success"
}
```

Then `/napi/api/stored/1234,5678` should return:

```
{
  "items": [
    {
      "name": "1234",
      "type": "Stored post"
    },
    {
      "name": "5678",
      "type": "Stored post"
    }
  ],
  "message": "success"
}
```

**Comment by Bhargav-Rao** [comment]
Thanks, looks good. Can you add the endpoint to the readme file?

**Comment by double-beep** [comment]
@Bhargav-Rao done

**Review by Bhargav-Rao — APPROVED** [review]

**Pull request merged**
